name: AccuKnox Vulnerability Scan
description: Scan Docker images using AccuKnox and push the results to the CSPM panel.

inputs:
  URL:
    default: "curl -sfL $URL | sh -s -- -b /usr/local/bin > /dev/null"
    description: 'URL to download accuknox vulnerability scanner'
    required: true 
  ACCUKNOX:
    default: "trivy"
    description: 'Name of tool'
    required: true
  docker_image:
    description: 'Defines docker_image variable with base name repo and dynamic tag from github.run_id'
    required: true
  dockerfile_context:
    description: 'The context of the Dockerfile to use for building the image.'
    required: true
    default: 'Dockerfile'
  cspm_url:
    description: 'The URL of the CSPM panel to push the scan results to.'
    required: true
  cspm_token:
    description: 'The token for authenticating with the CSPM panel.'
    required: true
  tenant_id:
    description: 'The ID of the tenant associated with the CSPM panel.'
    required: true


  
runs:
  using: 'composite'
  steps:
    - name: Download AccuKnox Vulnerability Scanner
      run: |
        curl -sfL ${{ github.event.inputs.URL }}" | sh -s -- -b /usr/local/bin > /dev/null
      shell: bash
    - name: Run AccuKnox Vulnerability Scanner
      run: |
        ${{ github.event.inputs.ACCUKNOX }}" image -f json ${{ inputs.docker_image }} -o results.json --quiet 
      shell: bash
      
    - name: Print AccuKnox Results
      run: cat results.json
      shell: bash
      
    - name: Push report to CSPM panel
      run: |
        curl --location --request POST "https://${{ inputs.cspm_url }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=TR&save_to_s3=false" --header "Authorization: Bearer ${{ inputs.cspm_token }}" --form "file=@\"./results.json\""
      shell: bash
