name: AccuKnox Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main  
     
      - name: Run AccuKnox CSPM Scan
        uses: ./
        with:
          token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzEwMzk0NzQ0LCJqdGkiOiJhNjg2NTc3YmRiNzM0NGVlOWY2MWIyMGU4NmQyYTlkMCIsImlzcyI6ImNzcG0uZGV2LmFjY3Vrbm94LmNvbSJ9.j32khSGqqb9BOO_4DRTSHyUj_W0x1qAeXeLmnxbvhlSeo0TFYtEKl1m3fOiIjF5iW9D6MCqC7JZxd9rUVJpPUATlaMVk4jrMYaupS6nSbB_oiNxUaVuKCRxKXSHOECnqczNjhBLBeTxX7VufNJyuQ9BQAAkPD6SJNu2IP6jk61VNELLoiIZNImhv3v7e0GwjIfGmhyWqwFqVgY-gX-gt2R88IOlEQB7vjz3XIap9miH8OnizODvAyQH_md6lawOg7hWGtjJnvwUgInp4s3JQur67CNBmXCMrfLl-nvTfaKbcsQVc9oaMiYKnMs5jk6Xif17g-ZNRlQ937yV5fdp0hw"
          tenant_id: "1069"
          severity: "CRITICAL"
          code: "0"
          repository_name: "udit-uniyal/vulnerable-to-test"
         
